# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spa', models.CharField(default='Question', max_length=149)),
                ('video_spa', models.CharField(default='Question', max_length=149)),
                ('name_eng', models.CharField(default='Question', max_length=149)),
                ('video_eng', models.CharField(default='Question', max_length=149)),
                ('thumbnail', models.ImageField(null=True, upload_to=questions.models.user_directory_path)),
                ('speaker', models.CharField(default='Speaker', max_length=149)),
                ('slug', models.SlugField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spa', models.CharField(default='Topic', max_length=149)),
                ('cover_spa', models.ImageField(null=True, upload_to=questions.models.user_directory_path)),
                ('name_eng', models.CharField(default='Topic', max_length=149)),
                ('cover_eng', models.ImageField(null=True, upload_to=questions.models.user_directory_path)),
                ('slug', models.SlugField(max_length=149)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Topic'),
        ),
    ]
