# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='issuu_spa',
            field=models.URLField(default='https://e.issuu.com/anonymous-embed.html?u=onelmedia&d=FILE_NAME', max_length=149),
        ),
        migrations.AddField(
            model_name='question',
            name='pdf_spa',
            field=models.FileField(null=True, upload_to=questions.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_eng',
            field=models.CharField(default='0000000', max_length=149),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_spa',
            field=models.CharField(default='0000000', max_length=149),
        ),
    ]
