# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20190208_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='issuu_spa',
            field=models.URLField(default='https://e.issuu.com/anonymous-embed.html?u=onelmedia&d=craig_groeschel', max_length=149),
        ),
    ]
