# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20190208_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='banner',
            field=models.ImageField(null=True, upload_to=questions.models.user_directory_path),
        ),
    ]
