# Generated by Django 2.1 on 2019-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pdf_link_spa',
            field=models.URLField(default='https://gls-demo-f4707.firebaseapp.com/DISCUSSIONGUIDES/DISC01/Craig_Groeschel.pdf', max_length=349),
        ),
    ]
